### ISSUE TITLE
xbitinfo with jupyterhub at dkrz

### ISSUE THREAD

**Issue by wachsylon** [observingClouds/xbitinfo#182] opened 2023-04-03 15:29 UTC
You probably know many of the following. xbitinfo, as it is now, seems to be *not usable* on Jupyterhub at DKRZ:

I am trying to run the lines from the README.

1. But before, when I install xbitinfo with conda, I install a very big julia with it. However, I cannot `import xbitinfo` on jupyterhub at dkrz because julia is still not found on path. Appending it to sys.path wont help.
2. When I install xbitinfo from the julia_optional path, I can import but I ran into dask errors (flatten wont work) even if I `.load()` the dataset before using xbitinfo.
3. When I open my target data set with `parallel=False`,  
    -  while get_bitinformation, I get
```
 /work/bm0021/conda-envs/eerie_io/lib/python3.11/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in divide
  return func(*(_execute_task(a, cache) for a in args))
```

- the resulting keepbits is negative so that I get:

```
 ValueError('keepbits must be zero or positive')

Traceback:
---------
  File "/work/bm0021/conda-envs/eerie_io/lib/python3.11/site-packages/dask/array/core.py", line 464, in apply_infer_dtype
    o = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/work/bm0021/conda-envs/eerie_io/lib/python3.11/site-packages/xbitinfo/bitround.py", line 9, in _np_bitround
    codec = BitRound(keepbits=keepbits)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/bm0021/conda-envs/eerie_io/lib/python3.11/site-packages/numcodecs/bitround.py", line 43, in __init__
    raise ValueError("keepbits must be zero or positive")
```

**Comment by aaronspring** [comment] 2023-04-04 08:27
Regarding 2 and 3, you can shooed between bitroubding done by implementation in julia or python. Does the error occur in both?

**Comment by aaronspring** [comment] 2023-04-04 08:29
1: usually we had trouble with the pip install. Conda worked quite well out of the box in my experience. I personally always used my own kernel created by the script and didn't use the hub because of these install issues I never understood

**Comment by observingClouds** [comment] 2023-04-04 15:42
To 3: could you please give a minimal reproducible example?

**Comment by wachsylon** [comment] 2023-04-05 08:05
I also built my own kernel for jupyterhub. I use python 3.11. and
```
mamba create -n xbitinfoenv -c conda-forge xbitinfo ipykernel
source activate xbitinfoenv
python -m ipykernel install --user --name xbitkernel
```
This installs a 100mb julia package without the option to choose between python/julia. 
Then, in a notebook I get
```
/home/k/k204210/.conda/envs/test/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

---------------------------------------------------------------------------
JuliaNotFound                             Traceback (most recent call last)
Cell In[1], line 1
----> 1 import xbitinfo

File ~/.conda/envs/test/lib/python3.11/site-packages/xbitinfo/__init__.py:8
      5 except ImportError:
      6     __version__ = "unknown"
----> 8 from .bitround import jl_bitround, xr_bitround
      9 from .graphics import plot_bitinformation, plot_distribution
     10 from .save_compressed import get_compress_encoding_nc, get_compress_encoding_zarr

File ~/.conda/envs/test/lib/python3.11/site-packages/xbitinfo/bitround.py:4
      1 import xarray as xr
      2 from numcodecs.bitround import BitRound
----> 4 from .xbitinfo import _jl_bitround, get_keepbits
      7 def _np_bitround(data, keepbits):
      8     """Bitround for Arrays."""

File ~/.conda/envs/test/lib/python3.11/site-packages/xbitinfo/xbitinfo.py:23
     21 already_ran = False
     22 if not already_ran and julia_installed:
---> 23     already_ran = install(quiet=True)
     24     jl = Julia(compiled_modules=False, debug=False)
     25     from julia import Main  # noqa: E402

File ~/.conda/envs/test/lib/python3.11/site-packages/xbitinfo/julia_helpers.py:22, in install(julia_project, quiet)
     15 """
     16 Install PyCall.jl and all required dependencies for xbitinfo.
     17 
     18 Also updates the local Julia registry.
     19 """
     20 import julia
---> 22 julia.install(quiet=quiet)
     24 julia_project, is_shared = _get_julia_project(julia_project)
     26 Main = init_julia()

File ~/.conda/envs/test/lib/python3.11/site-packages/julia/tools.py:78, in install(julia, color, python, quiet)
     61 """
     62 install(*, julia="julia", color="auto")
     63 Install Julia packages required by PyJulia in `julia`.
   (...)
     75     automatically.
     76 """
     77 if which(julia) is None:
---> 78     raise JuliaNotFound(julia, kwargname="julia")
     80 libpython = linked_libpython() or ""
     82 julia_cmd = [julia, "--startup-file=no"]

JuliaNotFound: Julia executable `julia` cannot be found.

If you have installed Julia, make sure Julia executable is in the
system PATH.  Alternatively, specify file path to the Julia executable
using `julia` keyword argument.

If you have not installed Julia, download Julia from
https://julialang.org/downloads/ and install it.
```

It is not described how I can `import xbitinfo` with choosing python or julia. The `implementation` kwarg exists for a function but I do not reach that point because the import does not work. Usually I am able to hack my notebook somehow to modify the path but does not work neither.

Luckily, I found that julia_optional brach from which I could install a version that works without julia using pip. Then I did:

```
import xarray as xr
omon3d=xr.open_mfdataset(
    "/work/bm1344/MPI-M/experiments/ngc2013/run_20480301T000000-20480331T235845/ngc2013_oce_ml_1mth_mean_20480401T000000Z.nc",
    engine="h5netcdf",
#    parallel=False
)
import xbitinfo as xb
to=omon3d[["to"]].load()
bitinfo = xb.get_bitinformation(to, dim="depth",implementation="python")
```

1. dim="depth" or dim="ncells" lead to a memory leak in dask. 80GBs memory were not enough for a single variable with a size about 1gb magnitude.
3. dim="time" gives you this:

```
----> 1 bitinfo = xb.get_bitinformation(to, dim="time",implementation="python")

File /work/bm0021/conda-envs/eerie_io/lib/python3.11/site-packages/xbitinfo/xbitinfo.py:236, in get_bitinformation(ds, dim, axis, label, overwrite, implementation, **kwargs)
    234         info_per_bit[var] = info_per_bit_var
    235 elif implementation == "python":
--> 236     info_per_bit_var = _py_get_bitinformation(ds, var, axis, dim, kwargs)
    237     if info_per_bit_var is None:
    238         continue

File /work/bm0021/conda-envs/eerie_io/lib/python3.11/site-packages/xbitinfo/xbitinfo.py:308, in _py_get_bitinformation(ds, var, axis, dim, kwargs)
    306 info_per_bit = {}
    307 logging.info("Calling python implementation now")
--> 308 info_per_bit["bitinfo"] = pb.bitinformation(X, axis=axis).compute()
    309 info_per_bit["dim"] = dim
    310 info_per_bit["axis"] = axis

File /work/bm0021/conda-envs/eerie_io/lib/python3.11/site-packages/xbitinfo/_py_bitinfo.py:160, in bitinformation(a, axis)
    156 sa = tuple(slice(0, -1) if i == axis else slice(None) for i in range(len(a.shape)))
    157 sb = tuple(
    158     slice(1, None) if i == axis else slice(None) for i in range(len(a.shape))
    159 )
--> 160 return mutual_information(a[sa], a[sb])

File /work/bm0021/conda-envs/eerie_io/lib/python3.11/site-packages/xbitinfo/_py_bitinfo.py:145, in mutual_information(a, b, base)
    143 def mutual_information(a, b, base=2):
    144     size = np.prod(np.broadcast_shapes(a.shape, b.shape))
--> 145     counts = bitpaircount(a, b)
    147     p = counts.astype("float") / size
    148     p = da.ma.masked_equal(p, 0)

File /work/bm0021/conda-envs/eerie_io/lib/python3.11/site-packages/xbitinfo/_py_bitinfo.py:138, in bitpaircount(a, b)
    136 for i in range(nbytes):
    137     s = (nbytes - 1 - i) * 8
--> 138     bitc = bitpaircount_u1((a >> s).astype("u1"), (b >> s).astype("u1"))
    139     bytewise_counts.append(bitc)
    140 return np.concatenate(bytewise_counts, axis=0)

File /work/bm0021/conda-envs/eerie_io/lib/python3.11/site-packages/xbitinfo/_py_bitinfo.py:101, in bitpaircount_u1(a, b)
     98 assert a.dtype == "u1"
     99 assert b.dtype == "u1"
    100 unpack_a = (
--> 101     a.flatten()
    102     .map_blocks(
    103         np.unpackbits,
    104         drop_axis=0,
    105         meta=np.array((), dtype=np.uint8),
    106         chunks=(a.size * 8,),
    107     )
    108     .astype("u1")
    109 )
    110 unpack_b = (
    111     b.flatten()
    112     .map_blocks(
   (...)
    118     .astype("u1")
    119 )
    120 index = ((unpack_a << 1) | unpack_b).reshape(-1, 8)

File /work/bm0021/conda-envs/eerie_io/lib/python3.11/site-packages/dask/array/core.py:2189, in Array.ravel(self)
   2179 """Return a flattened array.
   2180 
   2181 Refer to :func:`dask.array.ravel` for full documentation.
   (...)
   2185 dask.array.ravel : equivalent function
   2186 """
   2187 from dask.array.routines import ravel
-> 2189 return ravel(self)

File /work/bm0021/conda-envs/eerie_io/lib/python3.11/site-packages/dask/array/routines.py:1903, in ravel(array_like)
   1901 @derived_from(np)
   1902 def ravel(array_like):
-> 1903     return asanyarray(array_like).reshape((-1,))

File /work/bm0021/conda-envs/eerie_io/lib/python3.11/site-packages/dask/array/core.py:2219, in Array.reshape(self, merge_chunks, limit, *shape)
   2217 if len(shape) == 1 and not isinstance(shape[0], Number):
   2218     shape = shape[0]
-> 2219 return reshape(self, shape, merge_chunks=merge_chunks, limit=limit)

File /work/bm0021/conda-envs/eerie_io/lib/python3.11/site-packages/dask/array/reshape.py:248, in reshape(x, shape, merge_chunks, limit)
    245 if not merge_chunks and din > dout:
    246     x = x.rechunk({i: 1 for i in range(din - dout)})
--> 248 inchunks, outchunks = reshape_rechunk(x.shape, shape, x.chunks)
    249 # Check output chunks are not too large
    250 max_chunksize_in_bytes = reduce(mul, [max(i) for i in outchunks]) * x.dtype.itemsize

File /work/bm0021/conda-envs/eerie_io/lib/python3.11/site-packages/dask/array/reshape.py:91, in reshape_rechunk(inshape, outshape, inchunks)
     89     oleft -= 1
     90 if reduce(mul, outshape[oleft : oi + 1]) != din:
---> 91     raise NotImplementedError(_not_implemented_message)
     92 # TODO: don't coalesce shapes unnecessarily
     93 cs = reduce(mul, outshape[oleft + 1 : oi + 1])

NotImplementedError: 
Dask's reshape only supports operations that merge or split existing dimensions
evenly. For example:

>>> x = da.ones((6, 5, 4), chunks=(3, 2, 2))
>>> x.reshape((3, 2, 5, 4))  # supported, splits 6 into 3 & 2
>>> x.reshape((30, 4))       # supported, merges 6 & 5 into 30
>>> x.reshape((4, 5, 6))     # unsupported, existing dimensions split unevenly

To work around this you may call reshape in multiple passes, or (if your data
is small enough) call ``compute`` first and handle reshaping in ``numpy``
directly.
```

which is strange because there should not be a dask array after `load`. If I keep dask arrays by using
`to=omon3d[["to"]]#.load()`
bitinfo is an array of  `nan`s for `dim=time`. the other dims result in memory errors.

If you are interested, I can provide you permission to that file on Juypter if you like. It has 19GB. So I am not sure how to share that...

**Comment by wachsylon** [comment] 2023-04-05 08:18
I just redid this test on a compute node with 200GB memory and I am happy to finally have a result:
```
bitinfo = xb.get_bitinformation(to, dim="depth",implementation="python")
```
I think the memory peaked at about 100GB. I simply do not work with such configs in jupyterhub :)

**Comment by wachsylon** [comment] 2023-04-05 08:26
.... ok but the result is not reproducable.... I sometimes get 5 bits for 0.99 inflevel and sometimes 6 bits...  with that message:
```
Processing var: to for dim: depth:   0%|          | 0/1 [00:00<?, ?it/s]/work/bm0021/conda-envs/eerie_io/lib/python3.11/site-packages/dask/core.py:119: RuntimeWarning: divide by zero encountered in log
  return func(*(_execute_task(a, cache) for a in args))
```

**Comment by rsignell-usgs** [comment] 2023-04-07 17:56
Did you try installing `xbitinfo-python` from conda-forge?

**Comment by observingClouds** [comment] 2023-10-01 01:54
Closing this now as the divide by zeros should be fixed by #204. If there remains a reproducibility issue please feel free to reopen.

**Closed by observingClouds** 2023-10-01 01:54 UTC

**Comment by chiaral** [comment] 2023-11-28 22:13
I am writing a dataset to zarr after rounding it with xbitinfo.
This is done through a script that run on a AWS FARGATE cluster.

It works for almost all of my variables/zarr files (so I know that the problem is not my script)
But it fails on few atmospheric quantities I am coming across: precipitation, helicity, CIN. 
I get a similar error across these three dataset, in this image (apologies for being a picture, but this is from AWS logs, so i can't copy and paste it easily)
Basically it fails when I apply the rounding
```
ds_res = xb.xr_bitround(ds_res, keepbits)
```
and the error is below.
![Screenshot 2023-11-28 at 4 34 17 PM](https://github.com/observingClouds/xbitinfo/assets/8453445/47d2ca93-8412-4d77-9e14-6f01d381ed66)

in fact, precipitation has helicity and CIN can be negative, and acpcp happens to have negative values 
this is easy to reproduce, you can get the data from [here](https://noaa-gefs-retrospective.s3.amazonaws.com/GEFSv12/reforecast/2000/2000010100/c00/Days%3A1-10/acpcp_sfc_2000010100_c00.grib2) 
```
da = xr.open_dataset('acpcp_sfc_2000010200_c00.grib2')
import xbitinfo as xb
info_per_bit = xb.get_bitinformation(da, dim="longitude", implementation="python")
keepbits = xb.get_keepbits(info_per_bit, 0.99)
ds_bitrounded = xb.xr_bitround(da, keepbits)
ds_bitrounded.to_zarr("acpcp_bitrounded.zarr", encoding=encoding, mode="w")
```
and the error is
```
/home/ubuntu/miniconda3/envs/cfwi/lib/python3.11/site-packages/dask/core.py:121: RuntimeWarning: divide by zero encountered in log
  return func(*(_execute_task(a, cache) for a in args))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[8], line 4
      2 info_per_bit = xb.get_bitinformation(da, dim="longitude", implementation="python")
      3 keepbits = xb.get_keepbits(info_per_bit, 0.99)
----> 4 ds_bitrounded = xb.xr_bitround(da, keepbits)
      5 ds_bitrounded.to_zarr("acpcp_bitrounded.zarr", encoding=encoding, mode="w")

File ~/miniconda3/envs/cfwi/lib/python3.11/site-packages/xbitinfo/bitround.py:93, in xr_bitround(da, keepbits)
     91     da_bitrounded = da.copy()
     92     for v in da.data_vars:
---> 93         da_bitrounded[v] = xr_bitround(da[v], keepbits)
     94     return da_bitrounded
     96 assert isinstance(da, xr.DataArray)

File ~/miniconda3/envs/cfwi/lib/python3.11/site-packages/xbitinfo/bitround.py:99, in xr_bitround(da, keepbits)
     96 assert isinstance(da, xr.DataArray)
     97 keep = _keepbits_interface(da, keepbits)
---> 99 da = xr.apply_ufunc(_np_bitround, da, keep, dask="parallelized", keep_attrs=True)
    100 da.attrs["_QuantizeBitRoundNumberOfSignificantDigits"] = keep
    101 return da

File ~/miniconda3/envs/cfwi/lib/python3.11/site-packages/xarray/core/computation.py:1197, in apply_ufunc(func, input_core_dims, output_core_dims, exclude_dims, vectorize, join, dataset_join, dataset_fill_value, keep_attrs, kwargs, dask, output_dtypes, output_sizes, meta, dask_gufunc_kwargs, *args)
   1195 # feed DataArray apply_variable_ufunc through apply_dataarray_vfunc
   1196 elif any(isinstance(a, DataArray) for a in args):
-> 1197     return apply_dataarray_vfunc(
   1198         variables_vfunc,
   1199         *args,
   1200         signature=signature,
   1201         join=join,
   1202         exclude_dims=exclude_dims,
   1203         keep_attrs=keep_attrs,
   1204     )
   1205 # feed Variables directly through apply_variable_ufunc
   1206 elif any(isinstance(a, Variable) for a in args):

File ~/miniconda3/envs/cfwi/lib/python3.11/site-packages/xarray/core/computation.py:304, in apply_dataarray_vfunc(func, signature, join, exclude_dims, keep_attrs, *args)
    299 result_coords, result_indexes = build_output_coords_and_indexes(
    300     args, signature, exclude_dims, combine_attrs=keep_attrs
    301 )
    303 data_vars = [getattr(a, "variable", a) for a in args]
--> 304 result_var = func(*data_vars)
    306 out: tuple[DataArray, ...] | DataArray
    307 if signature.num_outputs > 1:

File ~/miniconda3/envs/cfwi/lib/python3.11/site-packages/xarray/core/computation.py:761, in apply_variable_ufunc(func, signature, exclude_dims, dask, output_dtypes, vectorize, keep_attrs, dask_gufunc_kwargs, *args)
    756     if vectorize:
    757         func = _vectorize(
    758             func, signature, output_dtypes=output_dtypes, exclude_dims=exclude_dims
    759         )
--> 761 result_data = func(*input_data)
    763 if signature.num_outputs == 1:
    764     result_data = (result_data,)

File ~/miniconda3/envs/cfwi/lib/python3.11/site-packages/xbitinfo/bitround.py:9, in _np_bitround(data, keepbits)
      7 def _np_bitround(data, keepbits):
      8     """Bitround for Arrays."""
----> 9     codec = BitRound(keepbits=keepbits)
     10     data = data.copy()  # otherwise overwrites the input
     11     encoded = codec.encode(data)

File ~/miniconda3/envs/cfwi/lib/python3.11/site-packages/numcodecs/bitround.py:43, in BitRound.__init__(self, keepbits)
     41 def __init__(self, keepbits: int):
     42     if keepbits < 0:
---> 43         raise ValueError("keepbits must be zero or positive")
     44     self.keepbits = keepbits

ValueError: keepbits must be zero or positive
```
for the record, I installed `xbitinfo` with `mamba install -c conda-forge xbitinfo-python` but I now noticed that it is `'0.0.4.dev1'` version.

**Comment by milankl** [comment] 2023-11-28 22:22
Looks like your `keepbits` is negative. This can happen because we count from the mantissa bits (keepbits=1 means keep 1 mantissa bit, throw away lesser significant bits). Could you paste the `info_per_bit` in here?

As a work-around I suggest to do a `keepbits = max(0,keepbits)`, to prevent it from being negative. This way you always preserve the exponent bits, which is usually fine.

@observingClouds should we not do a this max operation inside bitround? And then just throw a warning that your keepbits were negative but that we don't round the exponent bits?

**Comment by chiaral** [comment] 2023-11-29 13:59
@milankl thanks for the super fast response! really appreciated!

a quick follow up question, why though the 0.0.3 version is not available?

**Comment by observingClouds** [comment] 2023-11-29 15:11
Hi @chiaral 
The versioning is currently a bit off as "xbitinfo-python" is a feature of the [xbitinfo-feedstock](https://github.com/conda-forge/xbitinfo-feedstock) and we only introduced it after the release of xbitinfo 0.0.3.

As we do have some new features and changes since the release of 0.0.3 I hope I can make this consistent again soon.

Cheers,
Hauke
