### ISSUE TITLE
problem of 'gbk'

### ISSUE THREAD

**Issue by maker-slim** [observingClouds/xbitinfo#266] opened 2024-02-26 07:53 UTC
* xbitinfo version:0.03
* Python version:3.8
* Operating System:windows

### Description

After I installed the library, I selected a data file from the dataset submitted in Code Ocean to test the functionality of this library, and used the sample code given by the author to call it, but he kept prompting me with this error:

```python
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\anaconda3\envs\test\lib\site-packages\xbitinfo\__init__.py", line 8, in <module>
    from .bitround import jl_bitround, xr_bitround
  File "D:\anaconda3\envs\test\lib\site-packages\xbitinfo\bitround.py", line 4, in <module>
    from .xbitinfo import _jl_bitround, get_keepbits
  File "D:\anaconda3\envs\test\lib\site-packages\xbitinfo\xbitinfo.py", line 15, in <module>
    already_ran = install(quiet=True)
  File "D:\anaconda3\envs\test\lib\site-packages\xbitinfo\julia_helpers.py", line 22, in install
    julia.install(quiet=quiet)
  File "D:\anaconda3\envs\test\lib\site-packages\julia\tools.py", line 112, in install
    output, _ = proc.communicate()
  File "D:\anaconda3\envs\test\lib\subprocess.py", line 1015, in communicate
    stdout = self.stdout.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb0 in position 925: illegal multibyte sequence
```

### What I Did

I searched for the reason for this problem, I think it may be a problem with the encoding of the environment, I tried to modify the encoding of the environment, including specifying UTF-8, etc., but the modification did not bring changes, every time I debug, this error still appears, I want to ask the author whether this question is my operation problem. I'm a beginner and may make some mistakes, sorry.

**Comment by observingClouds** [comment] 2024-02-26 21:37
Hi @maker-slim,
Could you please provide a minimal working/failing example with the packages that you imported and the code you executed?
Thanks!

**Comment by maker-slim** [comment] 2024-02-27 02:48
I'm trying to process my data：import xarray as xr
from scipy.io import loadmat
data_dict = loadmat('datadumps/test/2ASK/test_2ASK.mat')
np_data = data_dict['phd_save']
xr_data = xr.DataArray(np_data)  and then I'm trying to call this library，I'm adding a breakpoint to the import library sentence：
import xbitinfo as xb，Then I debugged it, and he just reported the error：Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\anaconda3\envs\test\lib\site-packages\xbitinfo\__init__.py", line 8, in <module>
    from .bitround import jl_bitround, xr_bitround
  File "D:\anaconda3\envs\test\lib\site-packages\xbitinfo\bitround.py", line 4, in <module>
    from .xbitinfo import _jl_bitround, get_keepbits
  File "D:\anaconda3\envs\test\lib\site-packages\xbitinfo\xbitinfo.py", line 15, in <module>
    already_ran = install(quiet=True)
  File "D:\anaconda3\envs\test\lib\site-packages\xbitinfo\julia_helpers.py", line 22, in install
    julia.install(quiet=quiet)
  File "D:\anaconda3\envs\test\lib\site-packages\julia\tools.py", line 112, in install
    output, _ = proc.communicate()
  File "D:\anaconda3\envs\test\lib\subprocess.py", line 1015, in communicate
    stdout = self.stdout.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb0 in position 924: illegal multibyte sequence
So I didn't even test its functionality, just calling this library and it just reported an error

**Comment by observingClouds** [comment] 2024-02-27 07:45
It seems like this is an issue of the Julia installation. By default xbitinfo will install Julia if it isn't installed.
We run some [automatic tests](https://github.com/observingClouds/xbitinfo/blob/10a08dd3432caf82a8fc6bbea150fcd9b2db4f18/.github/workflows/ci.yaml#L120) that try to cover all OS including windows and they currently do not fail.

You might try the following:
- update your python to the one we test with (3.11)
- install Julia manually
- or use the python only implementation available with `conda install xbitinfo-python`

**Comment by maker-slim** [comment] 2024-02-27 09:11
I downloaded the software Julia, I don't know if you mean installing Julia software or plug-ins? I use pycharm, which doesn't seem to have julia-related plugins. As for the two other methods, I will try them now, thank you very much.

**Comment by maker-slim** [comment] 2024-02-27 10:08
Regarding the three solutions you gave, I tried them one by one, I first changed my python environment to 3.11 but it is still the same problem as before, and then I have indeed installed the software julia manually, and finally the installation command you said conda install xbitinfo-python I tried in the terminal but the installation failed。
        Dear author, I will probably tell you how I use your library, I have installed the software Julia, and then I created a new 3.11 python environment, installed some libraries and installed your library through the pip command, and then I tested it according to the code I showed you above, and then this problem appeared. I'd like to know how you tested and got error-free, sorry to bother you, but my assignment requires your method, and I'd appreciate it if I could help!!

**Comment by observingClouds** [comment] 2024-02-28 01:29
https://github.com/observingClouds/xbitinfo/blob/10a08dd3432caf82a8fc6bbea150fcd9b2db4f18/.github/workflows/ci.yaml#L144-L147

Here you can see that we do a "smoke test" on linux, Mac and windows. We install xbitinfo with pip and import it, just like you did in your mentioned example.

Could you please show us which error you get when you tried the `conda install xbitinfo-python` option?

**Comment by maker-slim** [comment] 2024-02-28 02:34
Yesterday the failure to type conda install xbitinfo-python should be the cause of the network, I tried it again and it was okay.
      I tried again today, I reinstalled Julia, I tried to type Julia in the anaconda prompt to start it and it succeed. Then I installed the xbitinfo library in the 3.11 version of Python, as you can see:
xarray                  2023.6.0
xbitinfo                0.0.3
Then I go into that environment and try to import this library:
>>> import xbitinfo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\anaconda3\envs\learn311\Lib\site-packages\xbitinfo\__init__.py", line 8, in <module>
    from .bitround import jl_bitround, xr_bitround
  File "D:\anaconda3\envs\learn311\Lib\site-packages\xbitinfo\bitround.py", line 4, in <module>
    from .xbitinfo import _jl_bitround, get_keepbits
  File "D:\anaconda3\envs\learn311\Lib\site-packages\xbitinfo\xbitinfo.py", line 15, in <module>
    already_ran = install(quiet=True)
                  ^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\learn311\Lib\site-packages\xbitinfo\julia_helpers.py", line 22, in install
    julia.install(quiet=quiet)
  File "D:\anaconda3\envs\learn311\Lib\site-packages\julia\tools.py", line 112, in install
    output, _ = proc.communicate()
                ^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\learn311\Lib\subprocess.py", line 1196, in communicate
    stdout = self.stdout.read()
             ^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb0 in position 923: illegal multibyte sequence
In the terminal he still tells me this error，I don't think there's anything wrong with my operation, but he keeps telling me about this error, which is very confusing.

**Comment by observingClouds** [comment] 2024-02-28 04:10
Do you really do `conda install xbitinfo-python` and not `conda install xbitinfo`? I'm surprised that you get Julia errors if you do the former of the too installation options.

**Comment by maker-slim** [comment] 2024-02-28 07:48
I did use the previous installation instruction and I was also confused. I just changed another computer and re-tested with python, this time still in version 3.11, only xbitinfo and xarray installed, julia was not even installed on this computer, but this time I imported xbitinfo and tested it without error.If there are no mistakes this time, it should be usable, but I don't even know how to solve this problem, but thank the author for answering my question.thanks！！

**Comment by observingClouds** [comment] 2024-03-04 23:19
Thanks for testing a different machine. It seems like your conda environment on your first machine might have some issues. Because our CI is not failing and we cannot reproduce your error due to the lack of windows machines, I am closing this issue. Glad you got the pure python implementation working.

**Closed by observingClouds** 2024-03-04 23:19 UTC
